In [5]:
# Question 1
from array import *
new_array=array('b',[1,2,3,4,5,6])
list=new_array.tolist()
print(list)


[1, 2, 3, 4, 5, 6]


In [6]:
# Question 2
import numpy as np
p=np.arange(9).reshape(3,3)
print(p)
result=np.trace(p)
print(result)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
12


In [1]:
# Question 3
import numpy as np
import numpy as np
x = np.array([[4, 7, 9], [15, 8, 11]])
print("Values bigger than 11", x[x>11])

Values bigger than 11 [15]


In [2]:
# Question 4
import numpy as np
a=np.array([(5,3),(2,4),(7,5)])
b=np.array([(4,5),(7,3),(8,6)])
c=np.array([a+b])
print(c)

[[[ 9  8]
  [ 9  7]
  [15 11]]]


In [4]:
#question 5
import numpy as np
x= np.random.randint(2, 10, size=(2,5))
print(x)
y = x- x.mean(axis=1, keepdims=True)
print(y)

[[4 7 3 4 7]
 [2 7 2 8 5]]
[[-1.   2.  -2.  -1.   2. ]
 [-2.8  2.2 -2.8  3.2  0.2]]
